apiVersion: v1
kind: Service
metadata:
  name: drones-server
  labels:
    app: drones-server
spec:
  type: LoadBalancer
  selector:
    app: drones-server
  ports:
  - protocol: UDP
    port: 5701
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drones-server
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drones-server
    spec:
      containers:
        - image: morshemesh/unitydronesserver
          name: drones-server
          ports:
          - containerPort: 5701
            protocol: UDP
            name: udp-port
